// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.34;

/// @dev implemented by the HonkVerifier generated by `pnpm build:verifier`, see WakeStakeVerifier.sol
interface IWakeStakeVerifier {
    function verify(bytes calldata _proof, bytes32[] calldata _publicInputs) external view returns (bool);
}
